project:
  type: website
  output-dir: docs
  resources:
    - data/

website:
  title: "GuardIAS Emerging Indicators"
  favicon: favicon.ico
  search: false
  navbar:
    left:
      - text: "Emerging Indicators"
        href: index.qmd
      - text: "Emerging Plots"
        href: species_plots.qmd
    right:
      - icon: github
        href: https://github.com/guardias-eu/indicators
      

format:
  html:
    theme: darkly
