project:
  type: website
  output-dir: docs
  resources:
    - data/

website:
  title: "GuardIAS Emerging Trends"
  favicon: favicon.ico
  search: false
  navbar:
    logo: images/assets/guardias_logo.png
    left:
      - text: "Emerging Trends"
        href: index.qmd
      - text: "Species Search"
        href: species_plots.qmd
    right:
      - icon: github
        href: https://github.com/guardias-eu/indicators
      

format:
  html:
    theme: darkly
