project:
  type: website
  output-dir: docs
  resources:
    - data/

website:
  title: "GuardIAS Emerging Indicators"
  favicon: favicon.ico
  navbar:
    left:
      - text: "Emerging Trends"
        href: index.qmd
      - text: "Species Plots"
        href: species_plots.qmd
      

format:
  html:
    theme: darkly
